### ISSUE TITLE
2.4 conflicts with buildcraft-all-7.99.24.8

### ISSUE THREAD

**Issue by A99011** [ConnorTron110/SCP-Lockdown-Issues#26]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 22-4-15 下午1:17
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Silicon (buildcraftsilicon)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at alexiy.secure.contain.protect.blocks.Block020.func_149645_b(Block020.java:82)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185901_i(BlockStateContainer.java:356)
	at buildcraft.silicon.plug.FacadeStateManager.isValidFacadeState(FacadeStateManager.java:182)
	at buildcraft.silicon.plug.FacadeStateManager.scanBlock(FacadeStateManager.java:262)
	at buildcraft.silicon.plug.FacadeStateManager.init(FacadeStateManager.java:213)
	at buildcraft.silicon.BCSilicon.init(BCSilicon.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3c291aad from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 43 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_321, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8020832616 bytes (7649 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 6 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -Xmx8G -Xms8G -XX:+AggressiveOpts -XX:+UseCompressedOops
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                          | Signature                                |
	|:----- |:------------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft           | 1.12.2       | minecraft.jar                                   | None                                     |
	| LCHI  | mcp                 | 9.42         | minecraft.jar                                   | None                                     |
	| LCHI  | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge               | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | scp                 | 2.4.0        | SCP_Lockdown-1.12.2-2.4.0-hotfix.jar | None                                     |
	| LCHI  | buildcraftlib       | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCHI  | buildcraftcore      | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCHI  | buildcraftbuilders  | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCHI  | buildcrafttransport | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCHE  | buildcraftsilicon   | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCH   | buildcraftcompat    | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCH   | buildcraftenergy    | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCH   | buildcraftfactory   | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |
	| LCH   | buildcraftrobotics  | 7.99.24.8    | buildcraft-all-7.99.24.8.jar                | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by davis697** [comment]
i tried to figure it out but cant i tried this minecraft:chest/0/veryfine/16/shulker_shell/2/0 what is wrong can you give me the correct one please

**Comment by ConnorTron110** [comment]
This is a known and fixed issue, see #7 For more information. A fix can be found on our  [Discord](https://discord.gg/NGdHJzh) in the announcement channel a few messages up, if you struggle to find it, here is the direct download link: 
https://cdn.discordapp.com/attachments/696000226754035733/905784560309108776/SCP_Lockdown-1.12.2-2.4.1-pre-release.jar

We do plan on making an actual curse forge release for this, however, there are a few unconfirmed critical bugs that we'd rather iron out so as to not come back to 1.12 when we make the jump to a higher version.

**Comment by davis697** [comment]
your the best thank you
________________________________

**Comment by A99011** [comment]
I am very sorry that I did not see and reply to your email in time
If you need anything else from me, please contact me.
Thank you very much for your reply!





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月23日(星期六) 晚上10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ConnorTron110/SCP-Lockdown-Issues] The latest version conflicts with buildcraft-all-7.99.24.8 (Issue #26)





 your the best thank you
 ________________________________
